"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const employerController_1 = require("../controllers/employerController");
const empAuth_1 = require("../Middlewares/empAuth");
const applicationController_1 = require("../controllers/applicationController");
const chatController_1 = require("../controllers/chatController");
const questionController_1 = require("../controllers/questionController");
const ExamController_1 = require("../controllers/ExamController");
const jobController_1 = require("../controllers/jobController");
const userController_1 = require("../controllers/userController");
const router = (0, express_1.Router)();
router.post("/generate-otp", employerController_1.generateOtp);
router.post("/register", employerController_1.EmployerRegister);
router.post("/postjob", empAuth_1.empAuth, employerController_1.postJob);
router.put("/editjob/:job", empAuth_1.empAuth, employerController_1.editJob);
router.post("/logout", employerController_1.removeEmpRefreshToken);
router.get("/employer-jobs/:id", empAuth_1.empAuth, employerController_1.getEmployerJobs);
router.get('/getapplicationsbyemp', empAuth_1.empAuth, applicationController_1.getApplicationByEmpIdCntrl);
router.post('/accept-application', empAuth_1.empAuth, chatController_1.acceptApplicationCntroller);
router.get('/fetchChats/:empId', chatController_1.fetchEmpChatsCntrlr);
router.post('/add-question', questionController_1.addQuestionCntrl);
router.get('/getquestions', questionController_1.getAllQuestionsCntrl);
router.post('/create-exam', ExamController_1.generateExam);
router.get('/job/:id', jobController_1.getSingleJOb);
router.get('/get-results/:exam', ExamController_1.getRestrl);
router.post('/enable-question', empAuth_1.empAuth, questionController_1.quesEnableCntrl);
router.post('/disable-question', empAuth_1.empAuth, questionController_1.quesDisbleCntrl);
router.put('/changepassword', empAuth_1.empAuth, userController_1.changePasswordCntrl);
router.get('/candidates/:page', empAuth_1.empAuth, employerController_1.getCandidatesCntrl);
router.put('/questionedit', empAuth_1.empAuth, questionController_1.QuestionEditCntrl);
router.get('/question/:id', empAuth_1.empAuth, questionController_1.getQuesrionByQId);
router.post('/create-chat', empAuth_1.empAuth, chatController_1.CreateChatCntrlr);
router.put('/job-true', empAuth_1.empAuth, employerController_1.updateStatustrue);
router.put('/job-false', empAuth_1.empAuth, employerController_1.updateStatusFalse);
router.get('/getappliedcount/:id', empAuth_1.empAuth, applicationController_1.applicationCount);
exports.default = router;
